### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by tanjosh** [MikeMpapa/CNNs-Speech-Music-Discrimination#1]
Please tell how to generate spectrograms and set segmentation parameters.

**Comment by MikeMpapa** [comment]
allthe parameters you are interested in are in the generateSpectrograms.py file. To run the file and generate the actual spectrograms run like :

python generateSpectrograms.py <path_to_data> <path_to_data_for_augmentation>

if no augmentation is needed just add "" as a second attribute

**Comment by tanjosh** [comment]
What about post processing? How did you convert npy output to RGB image?
