### ISSUE TITLE
weights

### ISSUE THREAD

**Issue by tanjosh** [MikeMpapa/CNNs-Speech-Music-Discrimination#2]
Can you add weights file so that it can be used for initialization for my network?

**Comment by MikeMpapa** [comment]
Yes I will upload it asap

**Comment by MikeMpapa** [comment]
You can download the trained model of CNN-SM from here: https://www.dropbox.com/sh/3fuxhit6h28dnk4/AAAxuRwCGDj6PeUub4znLWAaa?dl=0
