### ISSUE TITLE
Increasing number of classes

### ISSUE THREAD

**Issue by aitorbajo** [MikeMpapa/CNNs-Speech-Music-Discrimination#4]
Dear Mike

I am trying to train a 3-class based (music, speech and noise) audio classifier system using your tool. 

Do I have to change the given proto somehow? 

I trained a 2-classes (music, speech) model days ago and works fine, but when I increase the number of classes and do training, the output model does not work correctly even the training process has finished without errors. The classification gives always the same class as output (music in this case, the first one) without probabilities. 

Thank you so much in advance! ;-)

**Comment by MikeMpapa** [comment]
Hi ,

Thanks for your interest in my work.

To change the number of target classes just open the related .prototxt
file and search for the " num_output:" parameter at the last
Fully-Connected Layer. Currently is set up to 2 (Speech VS Music). Change
that to your preference.

Please "Star" my work if you found it useful.


Thank you,
Michalis


*Michalis Papakostas*

PhD Candidate
Heracleia - Human Centered Computing Lab
Department of Computer Science
University of Texas, Arlington

2018-02-14 12:20 GMT-06:00 aitorbajo <notifications@github.com>:
